export const programsData = {
  'exclusive': {
    label: 'EXCLUSIVE.',
    name: 'Exclusive One-on-One',
    heroDesc: "Your coach's time and focus, committed entirely to you.",
    price: 'Ksh 50,000',
    image: '/images/program-one-on-one.jpg',
    overview: "Exclusive One-on-One is the highest level of coaching at AMSC. For the full session, your coach's attention is on you alone — every rep observed, every adjustment made in the moment, and the entire programme built and driven around your body, your data, and your goals. Nothing about your training is generic; everything is calibrated to you.",
    features: [
      "Your coach's undivided time and attention for the entire session.",
      'Fully individualized programming built from your assessment and data.',
      'Real-time coaching, correction and load adjustment on every rep.',
      'Priority scheduling and complete session flexibility.',
      'Comprehensive movement screening and force profiling.',
      'Personalized nutrition, recovery and return-to-play guidance.',
    ],
    whoItsFor: 'Professional and elite athletes who need a coach fully dedicated to them — preparing for selection, competition, or a high-stakes return from injury.',
  },
  'one-on-one': {
    label: 'INDIVIDUAL.',
    name: 'Individualized Coaching',
    heroDesc: 'A programme built entirely around you, with hands-on coaching.',
    price: 'Ksh 30,000',
    image: '/images/program-one-on-one.jpg',
    overview: 'Individualized Coaching gives you your own programme — built from your assessment and performance data — with a coach guiding you through every session. You train with the full AMSC system and direct coaching support, sharing your coach’s time across a small number of athletes rather than one-to-one.',
    features: [
      'Fully individualized programming based on your assessment.',
      'Hands-on, coach-led sessions with direct guidance.',
      'Regular performance reviews and programme adjustments.',
      'Flexible scheduling within coached training windows.',
      'Movement screening and force profiling.',
      'Recovery and progression guidance.',
    ],
    whoItsFor: 'Committed athletes who want a programme built specifically for them and hands-on coaching, without needing a coach’s exclusive one-to-one time.',
  },
  'group': {
    label: 'STRUCTURED.',
    name: 'Performance Group Training',
    heroDesc: 'High-performance training in a structured group environment.',
    price: 'Ksh 15,000',
    image: '/images/program-group.jpg',
    overview: 'Performance Group Training delivers the AMSC system within a structured group environment. Athletes train together through periodized programs designed for long-term development.',
    features: [
      'Periodized training cycles built for long-term development.',
      'Movement efficiency and force production progression.',
      'Structured performance benchmarks.',
      'Professional training environment with coaching oversight.',
      'Small group sizes for quality coaching attention.',
      'Regular performance testing and progress tracking.',
    ],
    whoItsFor: 'Athletes who thrive in a competitive group environment and want structured, coach-led training without the premium of individual coaching.',
  },
  'online': {
    label: 'FLEXIBLE.',
    name: 'Online Performance Training',
    heroDesc: 'Structured programming for athletes training remotely.',
    price: 'Ksh 12,000',
    image: '/images/program-online.jpg',
    overview: 'Online Performance Training brings the AMSC system to athletes who train independently. You receive structured programming, video guidance, and systematic progression — built for execution anywhere.',
    features: [
      'Monthly structured training plans.',
      'Video-guided exercise standards.',
      'Progressive overload and capacity tracking.',
      'Built for independent execution with system accountability.',
      'Regular check-ins and program updates.',
      'Access to the AMSC exercise library.',
    ],
    whoItsFor: 'Athletes and driven individuals who train independently but want the structure and accountability of a proven performance system.',
  },
  'youth': {
    label: 'DEVELOPMENTAL.',
    name: 'Youth Athletic Development',
    heroDesc: 'Building athletic foundations for the next generation.',
    price: 'Ksh 10,000',
    image: '/images/jerome-lunge.jpg',
    overview: 'Youth Athletic Development focuses on building proper athletic foundations for young athletes aged 10–17. We develop movement competency, physical literacy, and long-term athletic capacity.',
    features: [
      'Age-appropriate strength and movement training.',
      'Speed and coordination development.',
      'Injury prevention through proper movement mechanics.',
      'Long-term athletic development pathway.',
      'Sport-specific movement preparation.',
      'Fun, engaging training environment.',
    ],
    whoItsFor: 'Young athletes aged 10–17 who want to build a strong athletic foundation, regardless of their primary sport.',
  },
  'consulting': {
    label: 'INSTITUTIONAL.',
    name: 'Team & School Performance Consulting',
    heroDesc: 'Performance system implementation for teams and institutions.',
    price: 'Contact',
    image: '/images/program-consulting.jpg',
    overview: 'Team & School Consulting brings the AMSC Performance System to organizations. We work with teams, schools, and sports programs to implement structured athletic development at scale.',
    features: [
      'Performance system design and implementation.',
      'Coach education and development programs.',
      'Athlete screening and assessment protocols.',
      'Periodization planning for team schedules.',
      'Performance monitoring and reporting systems.',
      'Ongoing consultation and system refinement.',
    ],
    whoItsFor: 'Sports teams, schools, academies, and organizations looking to implement a structured performance development system.',
  },
};
