export const programsData = {
  'one-on-one': {
    label: 'DIRECT.',
    name: 'One-on-One Coaching',
    heroDesc: 'The highest level of individualized athletic development at AMSC.',
    price: 'Ksh 30,000',
    image: '/images/program-one-on-one.jpg',
    overview: 'One-on-One Coaching is designed for athletes who require direct, individualized oversight at every stage of their development. Each session is built specifically for you — your movement profile, your performance data, your goals.',
    features: [
      'Fully customized training programs based on individual assessment.',
      'Direct coach access and real-time accountability.',
      'Weekly performance reviews and program adjustments.',
      'Priority scheduling and session flexibility.',
      'Comprehensive movement screening and force profiling.',
      'Personalized nutrition and recovery guidance.',
    ],
    whoItsFor: 'Professional athletes, competitive athletes preparing for selection or tournaments, and individuals recovering from injury who need precision-guided progression.',
  },
  'group': {
    label: 'STRUCTURED.',
    name: 'Performance Group Training',
    heroDesc: 'High-performance training in a structured group environment.',
    price: 'Ksh 15,000',
    image: '/images/program-group.jpg',
    overview: 'Performance Group Training delivers the AMSC system within a structured group environment. Athletes train together through periodized programs designed for long-term development.',
    features: [
      'Periodized training cycles built for long-term development.',
      'Movement efficiency and force production progression.',
      'Structured performance benchmarks.',
      'Professional training environment with coaching oversight.',
      'Small group sizes for quality coaching attention.',
      'Regular performance testing and progress tracking.',
    ],
    whoItsFor: 'Athletes who thrive in a competitive group environment and want structured, coach-led training without the premium of 1-on-1 coaching.',
  },
  'online': {
    label: 'FLEXIBLE.',
    name: 'Online Performance Training',
    heroDesc: 'Structured programming for athletes training remotely.',
    price: 'Ksh 12,000',
    image: '/images/program-online.jpg',
    overview: 'Online Performance Training brings the AMSC system to athletes who train independently. You receive structured programming, video guidance, and systematic progression — built for execution anywhere.',
    features: [
      'Monthly structured training plans.',
      'Video-guided exercise standards.',
      'Progressive overload and capacity tracking.',
      'Built for independent execution with system accountability.',
      'Regular check-ins and program updates.',
      'Access to the AMSC exercise library.',
    ],
    whoItsFor: 'Athletes and driven individuals who train independently but want the structure and accountability of a proven performance system.',
  },
  'youth': {
    label: 'DEVELOPMENTAL.',
    name: 'Youth Athletic Development',
    heroDesc: 'Building athletic foundations for the next generation.',
    price: 'Ksh 10,000',
    image: '/images/jerome-lunge.jpg',
    overview: 'Youth Athletic Development focuses on building proper athletic foundations for young athletes aged 10–17. We develop movement competency, physical literacy, and long-term athletic capacity.',
    features: [
      'Age-appropriate strength and movement training.',
      'Speed and coordination development.',
      'Injury prevention through proper movement mechanics.',
      'Long-term athletic development pathway.',
      'Sport-specific movement preparation.',
      'Fun, engaging training environment.',
    ],
    whoItsFor: 'Young athletes aged 10–17 who want to build a strong athletic foundation, regardless of their primary sport.',
  },
  'consulting': {
    label: 'INSTITUTIONAL.',
    name: 'Team & School Performance Consulting',
    heroDesc: 'Performance system implementation for teams and institutions.',
    price: 'Contact',
    image: '/images/program-consulting.jpg',
    overview: 'Team & School Consulting brings the AMSC Performance System to organizations. We work with teams, schools, and sports programs to implement structured athletic development at scale.',
    features: [
      'Performance system design and implementation.',
      'Coach education and development programs.',
      'Athlete screening and assessment protocols.',
      'Periodization planning for team schedules.',
      'Performance monitoring and reporting systems.',
      'Ongoing consultation and system refinement.',
    ],
    whoItsFor: 'Sports teams, schools, academies, and organizations looking to implement a structured performance development system.',
  },
};
